## Basic Configuration
baseurl = "https://www.cslsolucoesembd.com.br/"
title = "CSL Soluções em Banco de Dados"
languageCode = "en-us"
contentdir = "src/content"
datadir = "src/data"
layoutdir = "src/layouts"
publishdir = "dist"
staticdir = "src/static"
themesdir = "src/themes"
builddrafts = false
canonifyurls = false
author = "Cleysson Lima"
#theme = "goa"

## Hugo Built-in Features
#disqusShortname = "https-shenoybr-github-io-hugo-goa-demo" # Comment out to disable Disqus.
#googleAnalytics = "XYZ"
enableRobotsTXT = true

## Site Settings
[params]
author = "CSL Soluções em Banco de Dados"
intro = "Consultoria Especialiazada em Banco de Dados"
description = "Cuidamos dos seus dados enquanto você dorme tranquilo, entre em contato e faça o seu orçamento."
authorimage = "headshot.jpg"
dateformat = "Fevereiro 27, 2019"

## Site Meta Settings
[params.meta]
description = "CSL Soluções em Banco de Dados"
keywords = "cleyssonlima,blog,dba,postgresql,sql server,oracle,mysql,banco de dados"

## Social Accounts
[params.social]
github = "cleyssonlima"
instagram = "cslsolucoesembd"
twitter = "cslsolucoesembd"
email = "cleyssondba@gmail.com"

## Extras
[params.extra]
copyright = "Direitos reservados © 2019 - CSL Soluções em BD" 
poweredby = false
highlightjs = false

## Main Menu
[[menu.main]]
    name = "blog"
    weight = 100
    identifier = "blog"
    url = "/blog/"
[[menu.main]]
    name = "about"
    identifier = "about"
    weight = 200
    url = "/about/"
[[menu.main]]
    name = "coderag"
    identifier = "coderag"
    weight = 300
    url = "/coderag/"
